import Instagram from "../../public/instagram.svg";
import Twitter from "../../public/twitter.svg";
import Linkedin from "../../public/linkedin.svg";
import Github from "../../public/github.svg";
import SocialButton from "../../components/SocialButton";
import Link from "next/dist/client/link";
import Head from "next/head";
import Navbar from "../../components/Navbar";
import Profile from "../../public/avatartion.png";
import Image from "next/dist/client/image";

export default function about() {
  return (
      <>
      <Head>
        <title>About - Vineet Jassal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/avatartion.png" />
      </Head>
      <Navbar />
      <h1 className="font-bold text-6xl mt-16 mb-4">Passion Fuels Purpose!</h1>
      <div >
        <h2 className="font-semibold text-2xl">BIOGRAPHY</h2>
        <p className="text-xl mt-12"> Hi, I'm Vineet Jassal, a data scientist with a passion for analyzing and interpreting complex data to drive actionable insights and business strategies. With 1 years of experience in the field, I have worked on various projects involving data cleaning, data visualization, statistical analysis, and machine learning. <br /> <br /> I believe that data has the power to transform businesses and drive decision-making. By leveraging advanced analytics techniques and tools, I strive to uncover patterns, trends, and correlations in data that can provide valuable insights and inform strategic decision-making. <br /> <br /> Whether I'm working on predictive modeling, customer segmentation, or data-driven recommendations, I bring my strong analytical and problem-solving skills to every project I work on. I am always excited about exploring new data sets and applying innovative techniques to extract meaningful information. <br /> <br /> I look forward to the opportunity to apply my data science skills and contribute to your organization's success. </p>
      </div>
      <div className="two-column">
      <div className="image-container">
        <Image src={Profile} alt="" className="rounded-3xl border-2 border-black sm:w-[35rem] sm:h-[31rem] h-[20rem]"/>
      </div>
      <div className="text-container sm:mt-12 mt-6 border-2 border-black rounded-3xl pl-6 sm:h-[31rem] w-[22rem]">
        <h2 className="font-bold text-7xl mt-4 sm:mt-0">20+</h2>
        <p className="font-semibold text-3xl sm:text-5xl mb-16">Satisfied Clients</p>
        <h2 className="font-bold text-7xl">40+</h2>
        <p className="font-semibold text-3xl sm:text-5xl mb-16">Projects Completed</p>
        <h2 className="font-bold text-7xl">1+</h2>
        <p className="font-semibold text-3xl mb-4 sm:text-5xl">Years Of Experience</p>

      </div>
      <style jsx>{`
      h1{
            font-size:50px;
      }

        .two-column {
          display: flex;
          flex-wrap: wrap;
          align-items: center;
        }

        .image-container {
          flex: 1;
          margin-top:50px;
        }

        .text-container {
          flex: 1;
          margin-left:50px;
        }

        @media (max-width: 768px) {
          .two-column {
            flex-direction: column;
          }
          .text-container{
            margin-left:0px;
          }
        }
      `}</style>
    </div>
    <br />
      <section className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mb-4 font-sans">
        <div className="h-[40rem] rounded-3xl pt-4 pl-6 flex flex-col gap-16 bg-[url('/gradient-bg.jpg')] bg-cover sm:h-[35rem]">
        <h1 className="text-6xl font-bold">
          Education
          </h1>
          <div className="">
            <div>
              <h1 className="text-5xl font-bold">BS Mathematics (Hons.)</h1>
              <p className="text-2xl font-semibold">Kirori Mal College</p>
              <p className="text-xl font-normal">Nov,2022 - Jul,2026</p>
            </div>
            <div className="mt-8">
              <h1 className="text-5xl font-bold">Class XII</h1>
              <p className="text-2xl font-semibold">Sumermal Jain Public School</p>
              <p className="text-xl font-normal">Apr,2021 - Mar,2022</p>
            </div>
            <div className="mt-8">
              <h1 className="text-5xl font-bold">Class X</h1>
              <p className="text-2xl font-semibold">Sumermal Jain Public School</p>
              <p className="text-xl font-normal">Apr,2019 - Mar,2020</p>
            </div>
          </div>
        </div>
        <div className="h-[35rem] rounded-3xl p-8 bg-[url('/profile.png')] bg-cover bg-center" />
      </section>
<br />
    <section className="grid grid-cols-1 mb-4 font-sans">
        <div className="bg-zinc-200 h-[32rem] rounded-3xl p-10 flex flex-col bg-[url('/gradient-bg.jpg')] bg-cover md:h-[20rem]">
          <h1 className="text-5xl font-bold">
            Want to Work Together?
          </h1>
          <p className="flex-1 text-xl mt-4 font-semibold">
            Feel free to reach out for collaborations or just a friendly hello!
          </p>
          <a href="mailto:vineetjassal35@gmail.com" className="flex-1 text-xl mb-16">vineetjassal35@gmail.com</a>
          <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end">
            <Link className="bg-black text-center text-white font-medium py-3 px-12 rounded-full w-60 lg:w-auto" href={"mailto:vineetjassal35@gmail.com"}>
              Contact me
            </Link>
            <div className="flex items-center gap-4">
            <Link href={"https://www.linkedin.com/in/vineetjassal/"}  target="_blank">
              <SocialButton bgColor="linkedin">
                <Linkedin className="w-5 h-5" />
              </SocialButton>
              </Link> 
              <Link href={"https://twitter.com/vineet_ai"}  target="_blank">
              <SocialButton bgColor="twitter">
                <Twitter className="w-5 h-5" />
              </SocialButton>
              </Link>
              <Link href={"https://github.com/vineetjassal"}  target="_blank">
              <SocialButton>
                <Github className="w-5 h-5" />
              </SocialButton>
              </Link>
              <Link href={"https://www.instagram.com/vineetjassal/"}  target="_blank">
              <SocialButton  bgColor="instagram">
                <Instagram className="w-5 h-5" />
              </SocialButton>
              </Link>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}