import Head from "next/head";
import Navbar from "../../components/Navbar";
import ProjectPreview from "../../components/ProjectPreview";
import Instagram from "../../public/instagram.svg";
import Twitter from "../../public/twitter.svg";
import Linkedin from "../../public/linkedin.svg";
import Github from "../../public/github.svg";
import SocialButton from "../../components/SocialButton";
import Link from "next/dist/client/link";
import Typewriter from 'typewriter-effect';

export default function Home() {
  return (
    <>
      <Head>
        <title>Vineet Jassal - Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/avatartion.png" />
      </Head>

      <Navbar />

      <section className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mb-4 font-sans" id="home">
        <div className="bg-zinc-200 h-[45rem] rounded-3xl p-10 flex flex-col gap-16 bg-[url('/gradient-bg.jpg')] bg-cover sm:h-[30rem]">
          <h1 className="text-4xl md:text-5xl font-normal">
            Hello! I'm <span className="font-bold">Vineet</span>, a <br /> <span className="font-semibold inline-flex"><Typewriter
  options={{strings: ['Data Analyst','Data Engineer','React Developer'],autoStart: true,loop: true,}}/></span> with <span className="font-semibold">1</span> years <br /> of  experience.
          </h1>
          <p className="flex-1 text-xl">
          I care a lot about using data analysis for positive impact and enjoy creating user-centric, delightful, and human experiences through <br /> data-driven insights.
          </p>
          <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end">
            <Link className="bg-black text-center text-white font-medium py-3 px-12 rounded-full w-60 lg:w-auto" href={"#"} target="_blank">
              Resume
            </Link>
            <div className="flex items-center gap-4">
            <Link href={"https://www.linkedin.com/in/vineetjassal/"}  target="_blank">
              <SocialButton bgColor="linkedin">
                <Linkedin className="w-5 h-5" />
              </SocialButton>
              </Link> 
              <Link href={"https://twitter.com/vineet_ai"}  target="_blank">
              <SocialButton bgColor="twitter">
                <Twitter className="w-5 h-5" />
              </SocialButton>
              </Link>
              <Link href={"https://github.com/vineetjassal"}  target="_blank">
              <SocialButton>
                <Github className="w-5 h-5" />
              </SocialButton>
              </Link>
              <Link href={"https://www.instagram.com/vineetjassal/"}  target="_blank">
              <SocialButton  bgColor="instagram">
                <Instagram className="w-5 h-5" />
              </SocialButton>
              </Link>
            </div>
          </div>
        </div>
        <div className="h-[30rem] rounded-3xl p-8 bg-[url('/profile.png')] bg-cover bg-center" />
      </section>

      <section className="grid grid-cols-1 lg:grid-cols-2 gap-4 my-4 font-sans" id="project">
        <Link href={"https://github.com/Vineetjassal/Spotify-Data-Analysis"} target="_blank">
        <ProjectPreview
          name="Spotify Data Analysis"
          imageUrl="/spotify.png"
          dark
        />
        </Link>
        <Link href={"https://github.com/Vineetjassal/Netflix-Data-Analysis"} target="_blank">
        <ProjectPreview
          name="Netflix Data Analysis"
          imageUrl="/Netflix.png"
        />
        </Link>
        <Link href={"#"} target="_blank">
        <ProjectPreview
          name="Formula1 Analysis"
          imageUrl="/f1.png"
        />
        </Link>
        <Link href={"#"} target="_blank">
        <ProjectPreview
          name="Premier League EDA"
          imageUrl="/pre.png"
        />
        </Link>
      </section>

      <section className="grid grid-cols-1 mb-4 font-sans">
        <div className="bg-zinc-200 h-[32rem] rounded-3xl p-10 flex flex-col bg-[url('/gradient-bg.jpg')] bg-cover md:h-[20rem]">
          <h1 className="text-5xl font-bold">
            Want to Work Together?
          </h1>
          <p className="flex-1 text-xl mt-4 font-semibold">
            Feel free to reach out for collaborations or just a friendly hello!
          </p>
          <a href="mailto:vineetjassal35@gmail.com" className="flex-1 text-xl mb-16">vineetjassal35@gmail.com</a>
          <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end">
            <Link className="bg-black text-center text-white font-medium py-3 px-12 rounded-full w-60 lg:w-auto" href={"mailto:vineetjassal35@gmail.com"}>
              Contact me
            </Link>
            <div className="flex items-center gap-4">
            <Link href={"https://www.linkedin.com/in/vineetjassal/"}  target="_blank">
              <SocialButton bgColor="linkedin">
                <Linkedin className="w-5 h-5" />
              </SocialButton>
              </Link> 
              <Link href={"https://twitter.com/vineet_ai"}  target="_blank">
              <SocialButton bgColor="twitter">
                <Twitter className="w-5 h-5" />
              </SocialButton>
              </Link>
              <Link href={"https://github.com/vineetjassal"}  target="_blank">
              <SocialButton>
                <Github className="w-5 h-5" />
              </SocialButton>
              </Link>
              <Link href={"https://www.instagram.com/vineetjassal/"}  target="_blank">
              <SocialButton  bgColor="instagram">
                <Instagram className="w-5 h-5" />
              </SocialButton>
              </Link>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}