import Spotify from "../../public/spotify.png";
import Netflix from "../../public/netflix.png";
import f1 from "../../public/f1.png";
import pre from "../../public/pre.png";
import Image from "next/image";
import Head from "next/head";
import Navbar from "../../components/Navbar";
import Instagram from "../../public/instagram.svg";
import Twitter from "../../public/twitter.svg";
import Linkedin from "../../public/linkedin.svg";
import Github from "../../public/github.svg";
import SocialButton from "../../components/SocialButton";
import Link from "next/dist/client/link";

export default function Project() {
  return (
      <>
      <Head>
        <title>Project - Vineet Jassal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/avatartion.png" />
      </Head>
      <Navbar />
      <h1 className="text-5xl font-bold">Imagination Trumps Knowledge!</h1>
      <h3 className="text-2xl mt-4">My Project Works</h3>
      <br></br>
      <br></br>
      <ul>
      <div className="horizontal">
      <div className="two-column">
            <div className="image-container">
            <Image src={Spotify} alt="" className="rounded-3xl sm:h-[15rem] h-[10rem]"/>
            </div>
            <div className="text-container">   
        <h2 className="font-semibold sm:text-3xl text-2xl"><a href="https://github.com/Vineetjassal/Spotify-Data-Analysis" target="_blank">01 Spotify Data Analysis</a></h2>
        <h4 className="font-bold sm:text-5xl text-3xl">Featured Project</h4>
        <p className="sm:text-xl text-lg mt-4">Conducted Spotify data analysis using Python to extract valuable insights on user preferences, listening behaviors, and emerging music trends.</p>
            </div>
      </div>
      </div>
      </ul>
      <br></br>
      <ul>
      <div className="horizontal">
      <div className="two-column">
            <div className="image-container">
            <Image src={Netflix} alt="" className="rounded-3xl sm:h-[15rem] h-[10rem]" />
            </div>
            <div className="text-container">   
        <h2 className="font-semibold sm:text-3xl text-2xl"><a href="https://github.com/Vineetjassal/Netflix-Data-Analysis" target="_blank">02 Netflix Data Analysis</a></h2>
        <h4 className="font-bold sm:text-5xl text-3xl">Featured Project</h4>
        <p className="sm:text-xl text-lg mt-4">Performed Netflix data analysis using Python to extract insights on user viewing habits, popular genres, and recommendations for personalized content.</p>
            </div>
      </div>
      </div>
      </ul>
      <br></br>
      <ul>
      <div className="horizontal">
      <div className="two-column">
            <div className="image-container">
            <Image src={f1} alt="" className="rounded-3xl sm:h-[15rem] h-[10rem]" />
            </div>
            <div className="text-container">   
        <h2 className="font-semibold sm:text-3xl text-2xl"><a href="#" target="_blank">03 Formula1 Analysis</a></h2>
        <h4 className="font-bold sm:text-5xl text-3xl">Featured Project</h4>
        <p className="sm:text-xl text-lg mt-4">Using Python, I conducted detailed data analysis on Formula 1 racing, uncovering valuable insights, trends, and patterns to enhance performance strategies.</p>
            </div>
      </div>
      </div>
      </ul>
      <br></br>
      <ul>
      <div className="horizontal">
      <div className="two-column">
            <div className="image-container">
            <Image src={pre} alt="" className="rounded-3xl sm:h-[15rem] h-[10rem]"/>
            </div>
            <div className="text-container">   
        <h2 className="font-semibold sm:text-3xl text-2xl"><a href="#" target="_blank">04 Premier League EDA</a></h2>
        <h4 className="font-bold sm:text-5xl text-3xl">Featured Project</h4>
        <p className="sm:text-xl text-lg mt-4">I utilized Python to perform comprehensive data analysis on Premier League football, extracting valuable insights and patterns to optimize performance strategies and decision-making processes.</p>
            </div>
      </div>
      </div>
      </ul>
      <br></br>
      <br></br>
     
      <style jsx>{`
      .horizontal{
        border:2px solid;
        border-radius:40px;
        padding:30px;
        background:#fff;
      }

        .two-column {
          display: flex;
          flex-wrap: wrap;
        }

        .image-container {
          flex: 1;
        }
        
        .text-container {
          flex: 1;
          margin-left:50px;
      
        }

        @media (max-width: 768px) {
          .two-column {
            flex-direction: column;
          }
          .text-container {
            flex: 1;
            margin-left:10px;
            margin-top:40px;
          }
        }
      `}</style>
      <section className="grid grid-cols-1 mb-4 font-sans">
        <div className="bg-zinc-200 h-[32rem] rounded-3xl p-10 flex flex-col bg-[url('/gradient-bg.jpg')] bg-cover md:h-[20rem]">
          <h1 className="text-5xl font-bold">
            Want to Work Together?
          </h1>
          <p className="flex-1 text-xl mt-4 font-semibold">
            Feel free to reach out for collaborations or just a friendly hello!
          </p>
          <a href="mailto:vineetjassal35@gmail.com" className="flex-1 text-xl mb-16">vineetjassal35@gmail.com</a>
          <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end">
            <Link className="bg-black text-center text-white font-medium py-3 px-12 rounded-full w-60 lg:w-auto" href={"mailto:vineetjassal35@gmail.com"}>
              Contact me
            </Link>
            <div className="flex items-center gap-4">
            <Link href={"https://www.linkedin.com/in/vineetjassal/"}  target="_blank">
              <SocialButton bgColor="linkedin">
                <Linkedin className="w-5 h-5" />
              </SocialButton>
              </Link> 
              <Link href={"https://twitter.com/vineet_ai"}  target="_blank">
              <SocialButton bgColor="twitter">
                <Twitter className="w-5 h-5" />
              </SocialButton>
              </Link>
              <Link href={"https://github.com/vineetjassal"}  target="_blank">
              <SocialButton>
                <Github className="w-5 h-5" />
              </SocialButton>
              </Link>
              <Link href={"https://www.instagram.com/vineetjassal/"}  target="_blank">
              <SocialButton  bgColor="instagram">
                <Instagram className="w-5 h-5" />
              </SocialButton>
              </Link>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}